### ISSUE TITLE
[L] API - Ability to hold a DUP while in booking process.

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-api#358] opened 2024-03-22 22:43 UTC
#### Description:

As a park visitor, I want to have confidence that if there are passes available when I start booking a DUP that I will be able to successfully book one. 

One of the biggest pieces of feedback we get on DUP is that people try to book a pass and before they enter all their info and submit all the passes are sold out. Being able to hold your pass while you book for a specific amount of time would be ideal.

Passes are held for 7mins. **Updated to 7mins on May 14th**

#### Acceptance Criteria:
- API is set up, ready, and working so that we can connect it to front end tickets for DUP (please see dev checklist)

#### Development Checklist:

- [ ] Decrement counter from the facility once the user presses `Reserve`. If successful create a JWT that expires in X minutes
- [ ] Store JWT and related meta into a new partition in the main operational table
- [ ] Front-end must submit this JWT as part of the confirm checkout process.  If JWT expires, then the back-end will not accept the payload
- [ ] Cronjob to be run every 1-ish minutes in order to prune the temporary hold passes partition, re-adding those counts to the facility in question so that passes may be bookable again.
  - [ ] Run a schedule every minute ish checking for expired passes.
  - [ ] Look into scheduling the expiry as it happens as opposed to just running through the database every min

#### Dependencies

- Blocked by #344 
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- from discussion:

![Image](https://github.com/bcgov/parks-reso-api/assets/38668130/cebf51ed-a033-4173-af05-f13fbfaf72b7)

-

**Comment by Dianadec** [comment] 2024-04-08 16:46
Needs bigger discussion re architecture (@danieltruong & @marklise )

**Comment by JLWade** [comment] 2024-05-14 22:58
after conversation with @marklise we have updated hold time and Mark is going to add that time to the ENV config instead of hardcoded so it is easy to change.

**Comment by manuji** [comment] 2024-05-22 22:55
Tested onTEST: **Pending**

* Verified that the passes get held if a user selects to book a pass, meanwhile, if it's the last pass, then the other users will see a disabled booking time card with the "Full" status. 
* Verified that the user can book the pass successfully during the time allocated.
* Else an error is displayed -> Issues related to existing the hold time is tested in a different ticket. 
* Please refer to the **issues** given below:

1. The timer starts count down from 7:12 instead of 7 minutes. 


https://github.com/bcgov/parks-reso-api/assets/65190263/7050f1a3-7547-443a-a090-df99ec6d5740

FYI @marklise @danieltruong @cameronpettit

**Comment by marklise** [comment] 2024-05-22 23:06
@manuji that display bug will be a front-end bug.  You can report it in the UI repo.

**Comment by manuji** [comment] 2024-05-22 23:08
Will do @marklise .

**Comment by manuji** [comment] 2024-05-27 17:23
Tested on TEST: **Passed**
* verified that this task has been completed. 
* Passing to PO review.

**Comment by meyerdarcie** [comment] 2024-05-27 22:58
Working as intended - moving to done.

**Closed by meyerdarcie** 2024-05-27 22:58 UTC
Labels: DUP
