### ISSUE TITLE
[L] DUP: Update AWS SDK to V3

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-api#362] opened 2024-04-08 23:35 UTC
#### Description:

Update AWS-SDK from V2 to V3. When using V2 it is fairly common to see warnings about outdated functionality along with a reminder V2 is nearing end of support. This task is go through the process of updating to V3, resolve all the warnings, and test the app to ensure any breaking changes caused from this update have been resolved.

[Amazons guide for Updating to V3](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating.html)

#### Acceptance Criteria:
Day use pass now uses AWS-SDK V3.

#### Development Checklist:

- [ ] all warnings about v2 to v3 have been resolved
- [ ] Maintain functionality
- [ ] API, Public, Admin now using V3

#### Dependencies

- Blocked by #336 
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- MPORTANT: Switching to V3 will cause successful tests to fail in the GH environment. The issue has something to do with the asynchronous startup of DynamoDB. You MUST incorporate a `sleep` command into the on-pr test routine to WAIT for DynamoDB to be ready by the time tests run. Also use `--runInBand` to run tests in series to reduce the consecutive dynamodb load. Review [here](https://github.com/bcgov/bcparks-ar-api/pull/331/commits/775ab3f2d98520294c00ca2cb475053666c2d2fc) to see implementation
-

**Comment by Dianadec** [comment] 2024-05-08 20:50
May want to wait to do this until the SAM update is done. We'll move this to the following sprint (as per sprint planning convo)

**Comment by JLWade** [comment] 2024-05-28 18:42
Notes from refinement May 28, 2024:
- needs to be done, but wait until SAM is done (#336 )
- V2 SDK is still good until Sept (probably)

**Comment by Dianadec** [comment] 2024-07-11 18:44
Done but can't be released until SAM stuff is done

**Comment by Christopher-walsh22** [comment] 2024-10-23 18:52
Just thought I would write a comment on this ticket because I think it should either remain in QA until an issue is discovered from it, or be closed. 

There isn't any front end functionality that has been changed from this implementation of this ticket. If there is any issues that arise from this upgrade it would be discovered during the testing of the SAM API ticket.  During that process if any SDK errors arise it will be obvious from the logs, and to this point none have popped up. 

@manuji  you have asked me for a list places/things you could check to determine if this work has been completed, we originally created this ticket because of the warnings displayed during building. I can confirm those are no longer appearing.  You should be able to check in your build logs aswell for any warnings of "AWS-SDKv2 requires upgrade". Aside from that I could show you where the version numbers are located. Let me know how you would like to proceed with this.

**Comment by Dianadec** [comment] 2024-10-23 22:18
Moving to blocked based on Chris' comment. @manuji  let us know your thoughts :). cc @LindsayMacfarlane

**Comment by manuji** [comment] 2024-10-23 22:21
Hi @Dianadec , as per @Christopher-walsh22 comment, I think it's safe for us to move this to Done. Thank you

**Comment by LindsayMacfarlane** [comment] 2024-11-06 20:53
Thank you @Christopher-walsh22  and @manuji for your work on this ticket. Based on recommendation (eeek - from 2 weeks ago) - I will now close!

**Closed by LindsayMacfarlane** 2024-11-06 20:53 UTC
Labels: DUP
